# Generated by Django 5.0.7 on 2024-08-01 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Inventory',
            new_name='No_of_guests',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='No_of_guests',
            new_name='Inventory',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='Name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='BookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
            preserve_default=False,
        ),
    ]
